name: Build, Scan and Push

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: sample-app
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Debug GitHub Context
        run: |
          echo "Repository=$GITHUB_REPOSITORY"
          echo "Ref=$GITHUB_REF"
          echo "Actor=$GITHUB_ACTOR"

      - name: Show OIDC Token Claims
        shell: bash
        run: |
          TOKEN=$(curl -s \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com" | jq -r '.value')

          python3 - <<EOF
          import base64, json
          payload = "$TOKEN".split(".")[1]
          payload += "=" * (-len(payload) % 4)
          print(json.dumps(json.loads(base64.urlsafe_b64decode(payload)), indent=2))
          EOF

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::899867382718:role/mygithubactionrole
          aws-region: ${{ env.AWS_REGION }}

      - name: Create ECR Repository if not exists
        run: |
          aws ecr describe-repositories --repository-names $ECR_REPOSITORY || \
          aws ecr create-repository --repository-name $ECR_REPOSITORY

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh
          sudo mv ./bin/grype /usr/local/bin

      - name: Scan with Grype
        run: |
          grype $ECR_REPOSITORY:$IMAGE_TAG

      - name: Tag Image
        run: |
          docker tag \
            $ECR_REPOSITORY:$IMAGE_TAG \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push Image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Trigger AWS Repository
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.AWS_TRIGGER_TOKEN }}" \
            https://api.github.com/repos/santhosh3007kumar/samplemainawspy/dispatches \
            -d '{"event_type":"scan-ecr-image"}'